apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: journiv-data
  namespace: journiv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
