apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres.postgres.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
  hostname:
    hostname: "login.sanderpeters.cloud"
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  bootstrapAdmin:
    user:
      secret: keycloak-bootstrap-admin
