apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanderpeters/homelab
    targetRevision: master
    path: apps/mariadb
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
