apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/keycloak/keycloak-k8s-resources/kubernetes?ref=26.7.2
  - keycloak.yaml
  - httproute.yaml

patches:
  - path: delete-crds.yaml
